version: "3.9"
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
#      - TEMPLATES_AUTO_RELOAD=True
#      - FLASK_APP=app:app.py
    volumes:
      - .:/app
  db:
    image: "postgres"
    ports:
      - "50431:5432"
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=admin123
    volumes:
      - ./data/db:/var/lib/postgresql/data